/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrewIndexRouteImport } from './routes/crew/index'
import { Route as CrewSlugRouteImport } from './routes/crew/$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CrewSlugIndexRouteImport } from './routes/crew/$slug/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrewRoute,
} as any)
const CrewSlugRoute = CrewSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CrewRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CrewSlugIndexRoute = CrewSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrewSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/crew': typeof CrewRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/crew/$slug': typeof CrewSlugRouteWithChildren
  '/crew/': typeof CrewIndexRoute
  '/crew/$slug/': typeof CrewSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/crew': typeof CrewIndexRoute
  '/crew/$slug': typeof CrewSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/crew': typeof CrewRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/ratings': typeof RatingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/crew/$slug': typeof CrewSlugRouteWithChildren
  '/crew/': typeof CrewIndexRoute
  '/crew/$slug/': typeof CrewSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/crew'
    | '/portfolio'
    | '/privacy'
    | '/ratings'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/crew/$slug'
    | '/crew/'
    | '/crew/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/ratings'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/crew'
    | '/crew/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/crew'
    | '/portfolio'
    | '/privacy'
    | '/ratings'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/crew/$slug'
    | '/crew/'
    | '/crew/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CrewRoute: typeof CrewRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  RatingsRoute: typeof RatingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/'
      fullPath: '/crew/'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof CrewRoute
    }
    '/crew/$slug': {
      id: '/crew/$slug'
      path: '/$slug'
      fullPath: '/crew/$slug'
      preLoaderRoute: typeof CrewSlugRouteImport
      parentRoute: typeof CrewRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/crew/$slug/': {
      id: '/crew/$slug/'
      path: '/'
      fullPath: '/crew/$slug/'
      preLoaderRoute: typeof CrewSlugIndexRouteImport
      parentRoute: typeof CrewSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CrewSlugRouteChildren {
  CrewSlugIndexRoute: typeof CrewSlugIndexRoute
}

const CrewSlugRouteChildren: CrewSlugRouteChildren = {
  CrewSlugIndexRoute: CrewSlugIndexRoute,
}

const CrewSlugRouteWithChildren = CrewSlugRoute._addFileChildren(
  CrewSlugRouteChildren,
)

interface CrewRouteChildren {
  CrewSlugRoute: typeof CrewSlugRouteWithChildren
  CrewIndexRoute: typeof CrewIndexRoute
}

const CrewRouteChildren: CrewRouteChildren = {
  CrewSlugRoute: CrewSlugRouteWithChildren,
  CrewIndexRoute: CrewIndexRoute,
}

const CrewRouteWithChildren = CrewRoute._addFileChildren(CrewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CrewRoute: CrewRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  RatingsRoute: RatingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
